import Head from 'next/head';
import Form from '@/components/Form';
import Header from '@/components/Header';
import ContainerCenter from '@/components/ContainerCenter/styles';
import Footer from '@/components/Footer';

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ContainerCenter>
        <h2>Contact</h2>
        <Form />
      </ContainerCenter>
      <Footer />
    </>
  );
}
