import Head from 'next/head';
import Form from '@/components/Form';
import Header from '@/components/Header';

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h2>Contact</h2>
      <Form />
    </>
  );
}
