// 3rd parties
import Head from 'next/head';
// Components
import Breadcrumb from '@/components/Breadcrumb';
import ContainerCenter from '@/components/ContainerCenter/styles';
import Form from '@/components/Form';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ContainerCenter>
        <Breadcrumb>
          <Breadcrumb.Link href="/">
            Home
          </Breadcrumb.Link>
          <Breadcrumb.Item>
            Contact
          </Breadcrumb.Item>
        </Breadcrumb>
        <h2>Contact</h2>
        <Form />
      </ContainerCenter>
      <Footer />
    </>
  );
}
