import { Form } from '@/components/Form/styles';
import GoogleAnalytics from '@/components/GoogleAnalytics';
import ModalResponsive from '@/components/modalResponsive';
import Navbar from '@/components/Navbar';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blank Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Form />
      <ModalResponsive />
      <GoogleAnalytics />
    </div>
  );
}
